### ISSUE TITLE
Sistema cose generiche

### ISSUE THREAD

**Issue by ivanpak** [TecWeb2021/TecWeb#19]
- [x] sostituisci placeholder javascript con placeholder HTML5

**Comment by federicochiarello** [comment]
Sostituiti nelle searchbar.
Nelle form non ancora. Però volevo capire, secondo voi quanto javascript vogliono che facciamo?
Levando creazione/rimozione placeholder si dimezza e resta solo il controllo degli errori nelle form.

@ivan-piacere devi rimuovere (tramite php) i placeholder nei value delle form quando crei la pagina per la creazione di un nuovo gioco/notizia, che servono per quando la form viene usata per modificare qualcosa di esistente e metterci i valori presi dal db.
