### ISSUE TITLE
Messaggi per IVAN

### ISSUE THREAD

**Issue by federicochiarello** [TecWeb2021/TecWeb#28]
@ivan-piacere 
ho aggiunto l'id a tutti i "contenitori" del contenuto delle pagine, nel farlo ho trovato delle cose strane.

- [ ] giocoSchedaTemplate.html ha il menu (id="submenu") dentro il div (class="container"). 

- [ ] in giocoRecensioneTemplate.html il menu  (id="submenu") è fuori al  div (class="container"). 

Entrambi sono da aggiornare perchè il menu è diventato un <ul>

- [ ] login e loginTemplate hanno dei div con classe diversa, non so se è fatto apposta o era ancora da sistemare

**Comment by ivanpak** [comment]
Sì, sono tutti file che non aggiornavo da tempo, come anche la maggior parte di quelli nella cartella template. Comunque grazie. Domani copia incollando da /html si dovrebbe sistemare tutto
